"""add_street and default

Revision ID: 48838b987dd6
Revises: f612ed7bfeb2
Create Date: 2023-12-25 12:12:05.809356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48838b987dd6'
down_revision: Union[str, None] = 'f612ed7bfeb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adresses', sa.Column('street', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adresses', 'street')
    # ### end Alembic commands ###