"""add_adress

Revision ID: 3e89c7d97ca1
Revises: 2fca43402ba5
Create Date: 2023-12-25 11:36:23.581679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e89c7d97ca1'
down_revision: Union[str, None] = '2fca43402ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresses',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adresses')
    # ### end Alembic commands ###